name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # daily refresh
  workflow_dispatch:        # lets you trigger it manually anytime
  push:
    branches: ["main"]

jobs:
  featured-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: featured-repos.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: imohitparkash/Gradient, imohitparkash/multi-agent-debate, imohitparkash/RotoAuth
